CREATE TABLE IF NOT EXISTS posts(
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  image_name TEXT,
  text TEXT NOT NULL,
  tags TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS post_comments(
  id BIGSERIAL PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS post_likes(
  id BIGSERIAL PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now());